name: backend CI

on:
  push:
    branches:
      - dev
      - main
    pull_request:
      branches:
        - dev
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Gave execute permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

  lint:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Install ktlint
        run: curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.4.1/ktlint && chmod a+x ktlint

      - name: Lint with ktlint
        run: ./ktlint 'src/**/*.kt'



